# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1

      - run: sudo apt install sshpass
      - run: npm install -g @angular/cli
      - run: npm i
      - run: ng config -g cli.warnings.versionMismatch false
      - run: ng build --no-progress --aot --prod --base-href /~poujoist/info7/
      - run: sshpass -p '${{ secrets.SSH_PASSWORD }}' scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r `pwd`/dist/angular-tour-of-heroes/* poujoist@transit.iut2.upmf-grenoble.fr:public_html/info7/
